# Generated by Django 3.0.8 on 2020-08-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0006_course_course_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree_of_Knowledge',
            new_name='TreeOfKnowledge',
        ),
    ]
