# Generated by Django 3.0.8 on 2020-07-28 14:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_number', models.CharField(max_length=25)),
                ('course_description', models.TextField(max_length=750)),
                ('course_slug', autoslug.fields.AutoSlugField(default='Course Slug', editable=True, max_length=150, populate_from='course_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('department_slug', autoslug.fields.AutoSlugField(default='Department Slug', editable=True, populate_from='department_name', unique=True)),
            ],
        ),
    ]
