# Generated by Django 3.0.8 on 2020-08-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0007_auto_20200803_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeofknowledge',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='edunet.Course'),
        ),
    ]
