# Generated by Django 3.0.8 on 2020-08-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0011_auto_20200811_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleOfKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_num', models.IntegerField()),
                ('puzzle_of_knowledge', models.TextField()),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='edunet.Course')),
            ],
        ),
    ]
