# Generated by Django 3.0.8 on 2020-08-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0012_puzzleofknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeofknowledge',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edunet.Course'),
        ),
    ]
