# Generated by Django 3.0.8 on 2020-08-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0013_auto_20200821_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleofknowledge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edunet.Course'),
        ),
        migrations.AlterField(
            model_name='treeofknowledge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edunet.Course'),
        ),
    ]
