# Generated by Django 3.0.8 on 2020-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0016_auto_20200825_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_season',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_structure',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_abbreviation',
            field=models.CharField(max_length=10),
        ),
    ]
