# Generated by Django 3.0.8 on 2020-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0017_auto_20200825_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_structure',
            field=models.TextField(max_length=500),
        ),
    ]
