# Generated by Django 3.0.8 on 2020-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_season',
            field=models.CharField(default='Course Season', max_length=25),
        ),
    ]
