# Generated by Django 3.0.8 on 2020-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0003_auto_20200730_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_of_knowledge',
            name='transcript_num',
            field=models.CharField(default='Transcript Number', max_length=3),
        ),
    ]
