# Generated by Django 3.0.8 on 2020-08-10 21:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0008_auto_20200803_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=150, populate_from='course_name', unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='department_name', unique=True),
        ),
    ]
