# Generated by Django 3.0.8 on 2020-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0014_auto_20200821_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_structure',
            field=models.TextField(default='Course Structure', max_length=500),
        ),
    ]
