# Generated by Django 3.0.8 on 2020-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edunet', '0015_course_course_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_structure',
            field=models.TextField(default='Course Structure', max_length=250),
        ),
    ]
